[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

# [[main]]
#     identifier = "categories"
#     name = "Categories"
#     url = "/categories"
#     weight = 3

# [[main]]
#     identifier = "tags"
#     name = "Tags"
#     url = "/tags"
#     weight = 4

[[main]]
    identifier = "donate"
    name = "Donate"
    url = "https://www.buymeacoffee.com/honcharenko"
    weight = 5


# Social Media Configuration

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/yhoncharenko/"
    weight = 1

# [[social]]
#     identifier = "instagram"
#     name = "Instagram"
#     url = "#"
#     weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/goncharik"
    weight = 3